{% set name = "pypushflow" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypushflow-{{ version }}.tar.gz
  sha256: f833565292dac5e4f34e7a0ce6768c784ce4cc6ef403680b95984ebfad23a394

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=46.4
    - wheel
    - pip
  run:
    - python >=3.7

test:
  imports:
    - pypushflow
  commands:
    - pip check
    - pytest --pyargs pypushflow --ignore "$(python -c "from pypushflow import tests;print(tests.__path__[0])")/concurrent/test_interrupt.py"
  requires:
    - pip
    - pytest >=7
    - pytest-subtests >=0.4
    - psutil >=5.8
    - mongita >=1
    - mongomock
    - numpy

outputs:
  - name: pypushflow
  - name: pypushflow-mx
    requirements:
      host:
        - python >=3.7
        - setuptools >=46.4
        - wheel
        - pip
      run:
        - python >=3.7
        - "{{ pin_subpackage('pypushflow', exact=True) }}"
        - pymongo >=3
    test:
      imports:
        - pypushflow
      commands:
        - pip check
        - pytest --pyargs pypushflow --ignore "$(python -c "from pypushflow import tests;print(tests.__path__[0])")/concurrent/test_interrupt.py"
      requires:
        - pip
        - pytest >=7
        - pytest-subtests >=0.4
        - psutil >=5.8
        - mongita >=1
        - mongomock
        - numpy
    build:
      noarch: python

about:
  home: https://gitlab.esrf.fr/workflow/pypushflow/
  summary: A task scheduler for cyclic and acyclic graphs
  dev_url: https://gitlab.esrf.fr/workflow/pypushflow/
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - woutdenolf
    - olofsvensson
    - payno
