{% set name = "pypushflow" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypushflow-{{ version }}.tar.gz
  sha256: 775c6384e29989bfb00658f00c9970e43ed225148353ac8e27b0ada4240e8138

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pypushflow
  commands:
    - pip check
    - pytest --pyargs pypushflow --ignore "$(python -c "from pypushflow import tests;print(tests.__path__[0])")/concurrent/test_interrupt.py"
  requires:
    - pip
    - pytest >=7
    - pytest-subtests >=0.4
    - psutil >=5.8
    - mongita >=1

outputs:
  - name: pypushflow
  - name: pypushflow-mx
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - {{ pin_subpackage('pypushflow', exact=True) }}
        - pymongo >=3
    test:
      imports:
        - pypushflow
      commands:
        - pip check
        - pytest --pyargs pypushflow --ignore "$(python -c "from pypushflow import tests;print(tests.__path__[0])")/concurrent/test_interrupt.py"
      requires:
        - pip
        - pytest >=7
        - pytest-subtests >=0.4
        - psutil >=5.8
        - mongita >=1
    build:
      noarch: python

about:
  home: https://gitlab.esrf.fr/workflow/pypushflow/
  summary: A task scheduler for cyclic and acyclic graphs
  dev_url: https://gitlab.esrf.fr/workflow/pypushflow/
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - woutdenolf
    - olofsvensson
    - payno
