{% set name = "pypushflow" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypushflow-{{ version }}.tar.gz
  sha256: 1a7326d39bb76a419f841f3700f2f40249330f486a683ba673cd4acd9e4045e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.4
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pypushflow
  commands:
    - pip check
    - pytest --pyargs pypushflow
  requires:
    - pip
    - pytest >=7
    - pytest-subtests >=0.4
    - psutil >=5.8
    - mongita >=1
    - mongomock
    - numpy
    - python {{ python_min }}

outputs:
  - name: pypushflow
  - name: pypushflow-mx
    requirements:
      host:
        - python {{ python_min }}
        - setuptools >=46.4
        - pip
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('pypushflow', exact=True) }}
        - pymongo >=3
    test:
      imports:
        - pypushflow
      commands:
        - pip check
        - pytest --pyargs pypushflow
      requires:
        - pip
        - pytest >=7
        - pytest-subtests >=0.4
        - psutil >=5.8
        - mongita >=1
        - mongomock
        - numpy
        - python {{ python_min }}
    build:
      noarch: python

about:
  home: https://gitlab.esrf.fr/workflow/pypushflow/
  summary: A task scheduler for cyclic and acyclic graphs
  dev_url: https://gitlab.esrf.fr/workflow/pypushflow/
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - woutdenolf
    - olofsvensson
    - payno
