{% set name = "pypushflow" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypushflow-{{ version }}.tar.gz
  sha256: bb292cf7a4fcd7096599b21686db81857ff779b9473f4b58d064b52dafe365ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pypushflow
  commands:
    - pip check
    - pytest --pyargs pypushflow
  requires:
    - pip
    - psutil >=5.8
    - mongita >=1
    - pytest >=7
    - pytest-subtests >=0.4

outputs:
  - name: pypushflow
    requirements:
      host: &id001
        - python >=3.6
        - pip
      run:
        - python >=3.6
  - name: pypushflow-mx
    requirements:
      host: *id001
      run:
        - python >=3.6
        - pypushflow =={{ version }}
        - pymongo >=4

about:
  home: https://gitlab.esrf.fr/workflow/pypushflow
  summary: A task scheduler for cyclic and acyclic graphs
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - woutdenolf
    - olofsvensson
    - payno
