{% set name = "pypushflow" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypushflow-{{ version }}.tar.gz
  sha256: bb292cf7a4fcd7096599b21686db81857ff779b9473f4b58d064b52dafe365ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 4

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pypushflow
  commands:
    - pip check
    - pytest --pyargs pypushflow
  requires:
    - pip
    - pytest >=7
    - pytest-subtests >=0.4
    - psutil >=5.8
    - mongita >=1

outputs:
  - name: pypushflow
  - name: pypushflow-mx
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - "{{ pin_subpackage('pypushflow', exact=True) }}"
        - pymongo >=3
    test:
      imports:
        - pypushflow
      commands:
        - pip check
        - pytest --pyargs pypushflow
      requires:
        - pip
        - pytest >=7
        - pytest-subtests >=0.4
        - psutil >=5.8
        - mongita >=1
    build:
      noarch: python

about:
  home: https://gitlab.esrf.fr/workflow/pypushflow
  summary: A task scheduler for cyclic and acyclic graphs
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - woutdenolf
    - olofsvensson
    - payno
